/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;
import java.util.Random;

public class Library {
    public int[] roll (int n){
        int[] dice = {1, 2, 3, 4, 5, 6};
        int[] arr = new int[n];
        Random random = new Random();
        for (int i = 0; i < n; i++) {
            int randomIndex = random.nextInt(5);
            arr[i] = dice[randomIndex];
        }
        return arr;
    }
    public boolean containsDuplicates(int[] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = 0; j < array.length; j++) {
                if (i != j && array[i] == array[j]) {
                    return true;
                }
            }
        }
        return false;
    }
    public float averageCalculator(int[] array) {
        int sum = 0;
        for (int number : array) {
            sum = sum + number;
        }
        return (float) sum / array.length;
    }
}
